---
title: "Case Study"
author: "Sergio Garcia-Rios (with edits)"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(labelled)
library(pander)
library(forcats)
library(stargazer)
```

```{r pressure, echo=FALSE}
lns <- haven::read_dta("~/Downloads/lns_full.dta")
lns <- haven::as_factor(lns, only_labelled = T)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

```{r}
lns %>% count(natprob) %>% 
  mutate(pct = round(prop.table(n), 3)) %>% pander()
```

```{r}
ggplot(lns) + geom_bar(aes(x = natprob)) + coord_flip()
```

```{r}
lns %>% 
  count(latprob) %>% 
  mutate(pct = round(prop.table(n), 3)) %>% 
  arrange(desc(pct)) %>% 
  pander() 
```

```{r}
ggplot(lns) + geom_bar(aes(x = latprob)) + coord_flip()
```


### Poor People can get ahead
```{r}
lns %>% 
  group_by(poordisc) %>% 
  summarise(pct = round(n() * 100 / nrow(lns),2)) # %>% pander

prop.table(table(lns$poordisc, lns$newgen), 2)

# drop 'dk' responses
lns$poordisc_r <- lns$poordisc
lns$poordisc_r[lns$poordisc == 'dk'] <- NA_character_
lns$poordisc_r <- fct_relevel(lns$poordisc_r, "strongly disagree", "somewhat disagree", "somewhat agree", "strongly agree")
summary(lns$poordisc_r)
```

```{r}
poor_can <- lns %>% 
  group_by(newgen) %>% 
  count(poordisc_r) %>% 
  mutate(prop = prop.table(n)) %>% 
  na.omit()
poor_can
```

```{r}
ggplot(poor_can) + geom_line(aes(x = newgen, y = prop, col = poordisc_r)) +
  scale_color_discrete(name = "Opinion", labels = c("Strongly Disagree", "Somewhat Disagree",
                                                    "Somewhat Agree", "Strongly Agree"))
```


```{r}
lns %>% 
  group_by(latdisc) %>% 
  summarise(pct = n())
```















